dependencies:
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2l=0
- scipy=0.18.0
- sqlite
- pip
- pip:
  - ipykernel==4.4.1
  - matplotlib==1.5.2
  - networkx
  - notebook==4.2.2
  - pandas==0.18.1
  - python-dateutil==2.5.3
