dependencies:
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2l=0
- pip=8.1.2=py35_0
- python=3.5.2=0
- scipy=0.18.0=np111py35_0
- pip
- pip:
  - ipykernel==4.4.1
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - jupyter==1.0.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - matplotlib==1.5.2
  - networkx==1.11
  - notebook==4.2.2
  - pandas==0.18.1
  - python-dateutil==2.5.3
